name: Sigma Plugin Dependency Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  update_and_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Reinstall all sigma plugins
        run: |
          rm -rf *.*.*
          ./setup-sigma-versions.sh
        working-directory: backend
        continue-on-error: true

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      - name: Push changes to new branch
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b "sigma-update"
          git add backend/*
          git commit -m 'update sigconverter backend plugins'
          git push --set-upstream origin sigma-update

      - name: Create Pull Request
        if: steps.git-check.outputs.modified == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Update sigconverter backend dependencies',
              owner,
              repo,
              head: 'dev-to-int-${{ github.sha }}',
              base: 'main',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
