name: Sigma Plugin Dependency Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  update_and_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Reinstall all sigma plugins
        run: |
          rm -rf *.*.*
          ./setup-sigma-versions.sh
        working-directory: backend
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            backend/*
